name: Publish And Deploy Demo
on: [push]

jobs:
  build-client-nuxt:
    runs-on: ubuntu-latest
    steps:

    # 下载源码
    - name: Checkout
      uses: actions/checkout@master
    # 客户端打包构建
    - name: Client Build
      uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn build
    - run: mkdir temp # 创建temp文件夹，用来装要传输到服务器的文件
    - run: cp -r .nuxt static nuxt.config.js package.json yarn.lock temp # 把要传输到服务器的文件复制到temp

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "temp/"
          REMOTE_HOST: "68.168.132.115"
          REMOTE_USER: "root"
          REMOTE_PORT: "27274"
          TARGET: "/root/blog/web"
          
    # 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: "68.168.132.115"
        username: "root"
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /root/blog/web
          yarn install --production
